from setuptools import setup, find_packages

setup(
    name='rag',
    version='0.0.1',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'langchain',
        'langchain-community',
        'langchain-core',
        'langchain-openai',
        'langchain-text-splitters',
        'llama-index-core',
        'llama-index-embeddings-langchain',
        'llama-index-llms-anyscale',
        'llama-index-llms-fireworks',
        'llama-index-llms-langchain',
        'llama-index-llms-openai',
        'llama-index-embeddings-openai',
        'llama-index-readers-s3',
        'llama-index-readers-file',
        'llama-index-vector-stores-mongodb==0.1.6',
        'streamlit',
        'fastapi',
        'uvicorn',
        'pymongo',
    ],
    author='Om Achrekar',
    author_email='om@scogo.in',
    description='A package to create your own custom RAG system based on your data built by Scogo.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/om-scogo/rag',
    classifiers=[
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.7',
)
